name: mirror_mac_address
description: A new flutter plugin project.
version: 0.0.1
author: anymuse

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  device_info: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cvte.mirror_mac_address
        pluginClass: MirrorMacAddressPlugin
